const Products = [
    {
       id: 1,
       title: "Stylish T-Shirt",
       image: ["/t-shirt1.png","/t-shirt2.png"],
       slug: "stylish-t-shirt",
       price: 1200,
       category: "Clothing",
       description: "A high-quality cotton t-shirt with a stylish design.",
       size: ["S", "M", "L", "XL"],
       color: ["red", "blue", "black"],
       qty: 1,
       discount: 10,
   },
   {
       id: 2,
       title: "Causal Wear t-Shirt",
       image:  ["/product1.png","/product2.png"],
       slug: "Causal wear t-Shirt",
       price: 1500, 
       category: "clothing",
       description: "A premium leather wallet with multiple compartments.",
       size: ["S", "M", "L", "XL"],
       color: ["green", "yellow", "black"],
       qty: 1,
       discount: 0,
   },
   {
       id: 3,
       title: "check-and linning shirt",
       image: ["/sell1.png","/sell2.png"],
       slug: "check-and-linning shirt",
       price: 3000,
       category: "shirt",
       description: "Comfortable and durable running shoes for daily wear.",
       size: ["S", "M", "L", "XL"],
       color: ["red", "blue", "black"],
       qty: 1,
       discount: 15,
   },
   {
       id: 4,
       title: " Jeans Shorts",
       image: ["/sell3.png","/arrival-img4.png"],
       slug: "",
       price: 5000,
       category: "Shorts",
       description: "A sleek smart watch with fitness tracking features.",
       size: ["S", "M", "L", "XL"],
       color: ["red", "blue", "black"],
       qty: 1,
       discount: 0,
   },
   
   ]
   export default Products